### ISSUE TITLE
Interface for layer/tile-fetch-function reference

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-server#10]
Because the GT server is supposed to be pluggable and generic, we can't strictly mandate the types of objects/information users will ultimately design their programs around. This means that we can't assume, for instance, that `UUID`s will always uniquely refer to layers. What people will provide is some means of referring to tiles and some proof that they can produce a tile on the basis of said reference; what we will provide is a means of using the reference, itself, as though it were tile data.

The existing MAML solution in Raster Foundry is actually quite close to this behavior already and such a structure happens to be useful for optimizing MAML resolution. In brief, we:
1. collect all sources from a given AST
2. only keep distinct elements (the set of sources)
3. resolve a tile/region corresponding to each source node in the set
4. rewrite the AST with tile literals in preparation for evaluation

Likely output for this transformation process:
 - TMS: `(Int, Int, Int) => Tile`
 - Batch/WCS/TIFF: `Extent => Raster`

Cf. https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/tile/src/main/scala/tool/TileResolver.scala

**Comment by jisantuc** [comment]
Solution currently implemented:

- to render something, you have to prove that you have a `Decode`-able source, and that after decoding, you can get to something that can be `Reified` (turned into a tile literal). See `MamlReificiation` https://github.com/geotrellis/geotrellis-server/pull/21/files#diff-5b01a5168f27c99666c3511fea5538efR13
