### ISSUE TITLE
{WCS|WMS|WMTS} endpoint can't serve layers with capital letters

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#110]
https://github.com/geotrellis/geotrellis-server/blob/a310bed89a24b4255f5a380d64d122d01ff11a83/ogc/src/main/scala/geotrellis/server/ogc/wcs/params/ParamMap.scala#L11

Parsing of params will force all layer names to lower case, which may result in mismatch to their actual names in sources. 

Ideal solution to this issue is to have a single class that parses parameters that can be used by both WMS and WCS endpoints.

**Comment by moradology** [comment]
This no longer seems to be the case. On commit 11ac302731e07fa23ca13ec8f2a2b7d41460c51e of branch `develop`, I'm quite clearly able to summon layers in WCS and WMS which have capital letters:
![image](https://user-images.githubusercontent.com/1977405/75708900-b2ea4e00-5c8f-11ea-8b4a-d3ed8501073c.png)
![image](https://user-images.githubusercontent.com/1977405/75708911-b7af0200-5c8f-11ea-86a7-71fb27259e45.png)
