### ISSUE TITLE
Layer definition elements unused in WMS GetCapabilities response

### ISSUE THREAD

**Issue by jfbourgon** [geotrellis/geotrellis-server#115]
Layer definition elements (title, abstract) are not properly rendered in WMS GetCapabilities response.

Following layer definition
```
layers = {
   hrdtm = {
        type = "simplesourceconf"
        name = "hrdtm"
        title = "High Resolution Digital Terain Model (HRDTM)"
        abstract = "High Resolution Digital Terain Model generated from LiDAR"
        source = {
            ...
```
will produce the following output.
```
<Layer queryable="false">
   <Name>hrdtm</Name>
   <Title>hrdtm</Title>
   <Abstract>hrdtm</Abstract>
...
```
Faulty code seems to be: https://github.com/geotrellis/geotrellis-server/blob/564ba5e846ab7d89ef65ff9ea7f865c5c261c86d/ogc/src/main/scala/geotrellis/server/ogc/wms/CapabilitiesView.scala#L105-L107

**Comment by pomadchin** [comment]
In WCS 1.1.0 there is no `Name` anymore.
