### ISSUE TITLE
Rendering interface

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-server#12]
We need to provide a means for users to provide their own information that is resolvable into a full rendering specification. We're targeting other scala users so that end-users of applications based on the GT server aren't unnecessarily constrained.

This is an opportunity to step back and reflect on various means of representing color mappings and their perspecuity. We might want to look to javascript libraries for inspiration (those people are in the trenches with color a lot more often than most programmers). [chromajs](https://github.com/gka/chroma.js/) is the library whose API seems simplest/most expressive to me.

Some code which probably approaches what we're looking for: https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/tile/src/main/scala/image/package.scala

**Comment by echeipesh** [comment]
Kind of an old issue at this point. We have recently added [RGB](https://github.com/geotrellis/maml/pull/120) MAML node that in conjunction with other notes gives the user pretty powerful way to do basic color correction and rendering. I think in the future we will develop from there.
