### ISSUE TITLE
`OGCLayer` not respect tile size parameters

### ISSUE THREAD

**Issue by notthatbreezy** [geotrellis/geotrellis-server#124]
## Problem Description

When using `OGCLayer` in a WMS service with tile size parameters the tile sizes returned from the server do not respect the requested tile size from the client. This manifests itself as "stretchy" tiles along the border of the source raster as the extent of the requested tile is outside the extent of the source raster and is thus clipped.

The screenshot below shows this problem - the RGB is a tiff rendered and QGIS and the other layer is WMS served from an adapted version of OGC Example for some NAIP imagery.

![image](https://user-images.githubusercontent.com/898060/59205042-f33cf580-8b6f-11e9-91f1-51ec73dc0e1b.png)

**Comment by echeipesh** [comment]
The response to window query should use `PaddedTile` in way similar to:

https://github.com/geotrellis/geotrellis-contrib/blob/94ccdebff8ce58f5f3d8e1f96046961bb6ba1a46/vlm/src/main/scala/geotrellis/contrib/vlm/LayoutTileSource.scala#L76-L85

One possible thing to watch out for, this is the second time this logic finds a reason to be called. Might mean we should have an `apply` that pads out a tile based on overlapping `RasterExtents`.

**Comment by moradology** [comment]
I'm having a difficult time reproducing this bug on `master` at the moment.
![image](https://user-images.githubusercontent.com/1977405/59699630-eb103600-91bf-11e9-9a03-6e40b2e549a8.png)
