### ISSUE TITLE
Automate geotrellis-server release process

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#127]
Use https://github.com/geotrellis/maml/pull/98 as reference.

**Comment by rossbernet** [comment]
@notthatbreezy -

You asked about the release process for GT server - this issue is going on our next sprint. Is this what you were referring to?

**Comment by notthatbreezy** [comment]
Yup, thanks.

**Comment by rossbernet** [comment]
So - is this done via:

https://github.com/geotrellis/geotrellis-server/issues/134

Do we have questions?

**Comment by echeipesh** [comment]
Confirm, this is done.
