### ISSUE TITLE
Use shapeless records to parse `properties` and extensions

### ISSUE THREAD

**Issue by jisantuc** [geotrellis/geotrellis-server#128]
According to the STAC spec for items, `datetime` is required, and `title` is common. Other extensions define more fields that should be in `properties`. In the current implementation, we just say "hey man, it's an object, best of luck" -- https://github.com/geotrellis/geotrellis-server/pull/122/files#diff-fe86990cd1594794f235a75cdf28870c -- which isn't super helpful for end users. We can't however just say "it's one of these case classes _and only one_ of these case classes," because any number of extensions should be available.

However! There's a light at the end of this tunnel. Because extensions have specific shapes that they expect in properties, we can build shapeless records to match those shapes, try to decode all of them, and then just `++` them up at the end, parameterizing `StacItem` over the type of `properties`, and just asking that we know how to encode and decode whatever the type of `properties` is.

The record types we build should be aliased, because otherwise we'll end up surfacing this absolute trainwreck to end-users:

``` scala
@ val y = ("baz" ->> "yup") :: HNil
@ typeOf(y) 
res9: reflect.runtime.package.universe.Type = TypeRef(
  ThisType(package shapeless),
  class ::,
  List(
    RefinedType(
      List(
        TypeRef(ThisType(package lang), class String, List()),
        TypeRef(SingleType(ThisType(package shapeless), object labelled), trait KeyTag, List(ConstantType(Constant("baz")), TypeRef(ThisType(package lang), class String, List())))
      ),
      SynchronizedOps()
    ),
    TypeRef(ThisType(package shapeless), trait HNil, List())
  )
)
```

**Comment by pomadchin** [comment]
[STAC4S](https://github.com/azavea/stac4s) addresses this issue differently.
