### ISSUE TITLE
Instrumentation + logging

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-server#14]
Tile servers are prone to confusing and deep performance difficulties. With this attempt to create a generic tile server with lessons learned from numerous applications, we'd like to be sure to properly instrument all of the pieces so that introspection is a relatively simple task.

### instrumentation
Kamon tracer instrumentation has been implemented for http4s. We should avail ourselves of this and of the surrounding tools: https://github.com/kamon-io/kamon-http4s. An upshot of this is that the `docker-compose` which brings up a cluster of machines devoted to tile serving should also bring up the necessary `zipkin` or `prometheus` service by which metrics can be viewed.

### logging
In general, we should aim to use `logger.info` and `logger.debug` freely. This means extending almost everything with `LazyLogging`. Ideally, `println` debugging done during the programming of this application can be preserved in `logger.info` and `logger.debug` statements which are judiciously added before finalizing a PR for merge.

**Comment by jisantuc** [comment]
In `Server.scala` --

- Prometheus reporter added to Kamon: https://github.com/geotrellis/geotrellis-server/blob/master/http4s/src/main/scala/geotrellis/server/http4s/Server.scala#L66
- Exposure of Prometheus reporter: https://github.com/geotrellis/geotrellis-server/blob/master/docker-compose.yml#L17-L24
