### ISSUE TITLE
Effect type bound to IO forces downstream consumers to use concrete effect type

### ISSUE THREAD

**Issue by jisantuc** [geotrellis/geotrellis-server#148]
### Overview

In [`LayerHistogram`](https://github.com/geotrellis/geotrellis-server/blob/develop/core/src/main/scala/geotrellis/server/LayerHistogram.scala) e.g., the effect type for all IO-ish calls is bound to `IO`. This prevents any consumers of gt-server from using the typeclasses with an abstract effect type or any other effect type.

I think it's the case from a read through that the only typeclass evidence we need on the effect type is `Sync`, which would require translating `IO { ... }` to `F.delay { ... }` and asking for an implicit for applicative evidence to call `pure` where necessary (or maybe we get that from `F[_]: Sync` -- I never remember where we get the syntax for `.pure`)

### Acceptance

- `LayerHistogram` and other typeclasses have an abstract effect type
-  the examples still work

**Comment by notthatbreezy** [comment]
Hitting this now for a project, might be worth prioritizing if we can

**Comment by pomadchin** [comment]
Closed via https://github.com/geotrellis/geotrellis-server/pull/284
