### ISSUE TITLE
WMS defaultStyle not working

### ISSUE THREAD

**Issue by cath222ou** [geotrellis/geotrellis-server#149]
I have defined a default style in DefaultStyle parameter for WMS. However, when I do a GetMap request without style name, the style is 'default' and not the style define in DefaultStyle parameter.

Below, this is the style part of layer on my configuration file with DefaultStyle defined to 'official' style:

        defaultStyle = "official"
        styles = [
			{
                name = "official"
                title = "Official"
                type = "colormapconf"
                color-map = ${color-maps.dem2}
                legends = [
                    {
                        format = "image/png"
                        width = 36
                        height = 36
                        online-resource = {
                            type = "simple"
                            href = "http://dy0a51yzxbhxw.cloudfront.net/images/canada-icon.png"
                        }
                    }
                ]

Below, are different GetMap requests (one without style name, one with style name 'default' and one with style name 'officiel'). You can see on images when I do GetMap without style name, this is the same result as when i do GetMap with 'default' style name. However, when I do GetMap without style name, I was expecting the result was the DefaultStyle (official).

SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-15311418.827202465,10517168.037228156,-7966581.2070160909,11455987.670955122&WIDTH=877&HEIGHT=112&LAYERS=arcticdem2m&**STYLES=**&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE

![image](https://user-images.githubusercontent.com/30536406/65721580-4cc22500-e078-11e9-8de1-9928684bffc5.png)

SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-15311418.827202465,10517168.037228156,-7966581.2070160909,11455987.670955122&WIDTH=877&HEIGHT=112&LAYERS=arcticdem2m&**STYLES=default**&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE

![image](https://user-images.githubusercontent.com/30536406/65721724-93178400-e078-11e9-878a-3b5836fa612d.png)

SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-15311418.827202465,10517168.037228156,-7966581.2070160909,11455987.670955122&WIDTH=877&HEIGHT=112&LAYERS=arcticdem2m&**STYLES=official**&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE

![image](https://user-images.githubusercontent.com/30536406/65721678-73805b80-e078-11e9-933d-09aafd8bc6cd.png)

Thank you

Sorry for the wrong label. Is not a "release" label.

**Comment by moradology** [comment]
No sweat about the labels and thank you for making the issue!
