### ISSUE TITLE
Decouple services and routers

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-server#15]
We should provide services in `geotrellis.server.core` and implementation specific to `http4s` in something like `geotrellis.server.http4s`. This will allow the services to be plugged into `akka-http` as necessary

**Comment by jisantuc** [comment]
Code is already written this way -- see e.g. wcs, tms, maml, cog imports in `Server.scala` https://github.com/geotrellis/geotrellis-server/blob/master/http4s/src/main/scala/geotrellis/server/http4s/Server.scala#L3-L6
