### ISSUE TITLE
Artefacts with hillshade MAML operation

### ISSUE THREAD

**Issue by cath222ou** [geotrellis/geotrellis-server#150]
When I use fhillshade MAML operation from the DEM data, It have artefacts on the GetMap result. On the example below, we see vertical and horizontal lines. The request GetMap use projection of original data (EPSG:3857) and a color-maps style.

`
SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=**EPSG:3857**&BBOX=-8212121.0951458206,10994397.212170906,-8204445.5172946611,11001294.913466308&WIDTH=967&HEIGHT=869&LAYERS=arcticdem2mhillshade&STYLES=greyscalemap&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE&
`
![image](https://user-images.githubusercontent.com/30536406/65901916-2ad1e680-e387-11e9-95fe-932ac112f87c.png)

We see the same thing for a GetMap request that uses a different projection than the original data.
`
SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=**EPSG:3978**&BBOX=780813.0364727308,2393130.123206886,786953.49875365547,2398648.2842432079&WIDTH=967&HEIGHT=869&LAYERS=arcticdem2mhillshade&STYLES=greyscalemap&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE
`
![image](https://user-images.githubusercontent.com/30536406/65901532-63bd8b80-e386-11e9-8648-d26e7febd7bd.png)

We see the same thing with color-ramps style.

![image](https://user-images.githubusercontent.com/30536406/65901817-f9591b00-e386-11e9-8083-62c2568fb5e5.png)

**Comment by pomadchin** [comment]
It is a 2 point issue now, if it is not, there would be a new issue created with a more precise descirption of the issue and task.

**Comment by pomadchin** [comment]
Using bilinear interpolation for reprojection operation resolves this issue:

![bilinear-nn](https://user-images.githubusercontent.com/4929546/77214300-ed077c80-6ae4-11ea-976e-61fefbaf903d.gif)
