### ISSUE TITLE
Cannot configure only one type of web map service

### ISSUE THREAD

**Issue by cath222ou** [geotrellis/geotrellis-server#151]
In the configuration file, when I try to configure only two of three web map service, the server cannot start. For example, if I configure WMS and WCS, but not WMST, the server cannot start.
I have the same problem if i configure all of types of web map service but that I keep "layer-definitions" list empty.

 Is this possible to configure only type of web map service i need ?

**Comment by pomadchin** [comment]
Hey @cath222ou thanks for reporting us about it, nice catch. Definitely sounds like a bug.
