### ISSUE TITLE
STAC - STAC version should be 0.8.0 (no RC)

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis-server#153]
`stac_version` should be `0.8.0` for the release candidate, according to [the JSON schema](https://github.com/radiantearth/stac-spec/blob/v0.8.0-rc1/item-spec/json-schema/item.json#L39)

**Comment by notthatbreezy** [comment]
Also we should test the validator on this once it is in RF - also this issue is in RF

**Comment by lossyrob** [comment]
I recommend using the schemas directly a la https://github.com/azavea/pystac/blob/develop/tests/utils.py#L122, stac-validator is currently lagging behind the 0.8 release, although I know folks are putting in effort in it in the near future.
