### ISSUE TITLE
STAC: Label Overviews cannot be null

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis-server#156]
According to the [schema in the spec](https://github.com/radiantearth/stac-spec/blob/v0.8.0-rc1/extensions/label/schema.json#L73), the `label:overview` property cannot be null. It is optional, therefore when the label:overview is not present, the property should not be serialized at all.

**Comment by notthatbreezy** [comment]
I think this is probably happening in the default `circe` printer, we'll have to adjust it from the default to have it not serialize `None` as `null` and instead omit those keys.
