### ISSUE TITLE
Add TIME parameter support to GetCoverage request

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#158]
When querying layers that have temporal component, for instance GeoTrellis spatiotemporal layer or a STAC catalog it should be possible to specify the time range for the query.

![Screen Shot 2019-10-09 at 5 31 26 PM](https://user-images.githubusercontent.com/1158084/66522150-c0bded80-eaba-11e9-8ca4-eaf5c8ff8652.png)

The parameter is described further in OGC specification document for WCS 1.0.0 (Section 10.2): https://portal.opengeospatial.org/files/05-076

This issue covers parsing the query, routing it to the catalog model and return an actual raster response.

It is possible that `TIME` parameter will be specified as a time range or a sequence of dates. Because we expect to be querying data-cube of rasters that already exist the expected result is a coverage that falls on or with-in times described. This parameter is specific to version 1.0.0 of WCS protocol

This is not officially part of the specification but seems to be a reasonable interpretation for our case.

**Comment by pomadchin** [comment]
We don't support WCS 1.0 anymore.
