### ISSUE TITLE
WCS 1.0.0 DescribeCoverage response may contain TemporalDomain

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#159]
WCS 1.0.0 `DescribeCoverage` response contains `domainSet` element 

WCS 1.0.0 Specification Section 8.3.2 

> The first of these elements, domainSet, describes the domain of the coverage offering – that is, the locations in space and/or time for which values or measures are available (whether by direct retrieval or by spatial interpolation). GetCoverage requests should retrieve meaningful data from the Coverage Offering if their spatial or temporal constraints (BBOX or BoundingBox, TIME, or Time) intersect the locations or times described in domainSet.

> domainSet must include a SpatialDomain (describing the spatial locations – whether discrete or continuous – for which coverages may be requested), a TemporalDomain (describing the time instants or intervals for which coverages may be requested), or both.

This issue to connect updated data model for coverage to WCS `DescribeCoverage` response such that available metadata is well represented.

Note that in case the source layer will be a GeoTrellis spatiotemporal layer the temporal ranges of populated layers will need to be written to the `AttributeStore` by user, as GeoTrellis layers can not efficiently query for availability of time slices, only attempt to read things at specific time interval. 

## Reference

`TM_Position` and `TM_PeriodDuration` are defined in [ISO_19108](http://people.ischool.berkeley.edu/~ryanshaw/pdf/ISO_19108.pdf)

**Comment by pomadchin** [comment]
We dropped WCS 1.0 support here https://github.com/geotrellis/geotrellis-server/pull/191
