### ISSUE TITLE
WCS 1.1.0 DescribeCoverage response may contain SpatialDomain

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#160]
WCS 1.1.0 DescribeCoverage response contains `Domain` element which may contain `SpatialDomain`

![Screen Shot 2019-10-09 at 5 50 59 PM](https://user-images.githubusercontent.com/1158084/66523222-5ce8f400-eabd-11e9-9327-4a6c6a2b5769.png)

This issue to connect updated data model for coverage to WCS 1.1.0 `DescribeCoverage` response such that available metadata is well represented.

**Comment by pomadchin** [comment]
Supressed by https://github.com/geotrellis/geotrellis-server/issues/188
