### ISSUE TITLE
Add interpolation to color configuration for WMS/WMTS

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#161]
`ColorMap` associates a range of breaks (raster values) with a color.

Currently rendering a raster results snapping each pixel value to the closest break value and assign it corresponding color value. As such the output raster may only have colors explicitly specified in the color ramp. This is how `Discrete` color rendering works in QGIS.

This issue is to add a rendering option that will interpolate option to rendering that takes place in WMS and WMTS endpoints. When enabled the assigned color is going to be interpolated (linearly) in the color space based on distance of the pixel value between two closest break values in the `ColorMap`.

**Comment by moradology** [comment]
The `RgbLerp` function [here](https://github.com/raster-foundry/raster-foundry/blob/51ec48b8c89d9d911421d640749bdc8361733691/app-backend/tile/src/main/scala/image/package.scala) interpolates just as described. Much of the rendering developed for RF could be used as a starting point for this
