### ISSUE TITLE
Use RasterSourceProvider to read COGs

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#174]
Currently we allow defining a COG layer through [`RasterSourceConf`](https://github.com/geotrellis/geotrellis-server/blob/develop/ogc-example/src/main/scala/geotrellis/server/ogc/conf/RasterSourceConf.scala) and supports COG reads through `GeoTiffRasterSource`. However, there is no way to specify using `GDALRasterSource`.

There configuration for the project should use new  [`RasterSourceProvider`](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/RasterSourceProvider.scala)

This would switch the source configuration to be uniform URI that could be interpreted by the provider interface.

Ref:
- https://github.com/locationtech/geotrellis/blob/master/store/src/main/scala/geotrellis/store/GeoTrellisRasterSourceProvider.scala
- https://github.com/locationtech/geotrellis/blob/master/gdal/src/main/scala/geotrellis/raster/gdal/GDALRasterSourceProvider.scala
- https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffRasterSourceProvider.scala

**Comment by CloudNiner** [comment]
Depends on locationtech/geotrellis#3191
