### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-server#183]
- [x] Start a new release branch:
```bash
$ git flow release start X.Y.Z
```
- [x] Rotate `CHANGELOG.md` (following [Keep a Changelog](https://keepachangelog.com/) principles)
- [x] Ensure outstanding changes are committed:
```bash
$ git status # Is the git staging area clean?
$ git add CHANGELOG.md
$ git commit -m "X.Y.Z"
```
- [x] Publish the release branch:
```bash
$ git flow release publish X.Y.Z
```
- [x] Ensure that CI checks pass
- [ ] Finish and publish the release branch:
    - When prompted, keep default commit messages
    - Use `X.Y.Z` as the tag message
```bash
$ git flow release finish -p X.Y.Z 
```

**Comment by pomadchin** [comment]
Closing this one since it has already been done.
