### ISSUE TITLE
GeoTrellis Server core types should be effect agnostic

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-server#193]
At this point all basic type classes (i.e. `ExtentReification` and similar) and functions that work with them are built around `IO`. 

It seems to me code can become more readable and more defined with abstracting over the effect type.

**Comment by pomadchin** [comment]
Looks like a duplicate of https://github.com/geotrellis/geotrellis-server/issues/148
I'll keep both issue still but connected.

**Comment by echeipesh** [comment]
It is DONE ! 🥇
