### ISSUE TITLE
WCS Rendering formats support

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-server#195]
At this point WCS GetCoverage can return data only as a tiff. It would be nice to have some rendering options support.

**Comment by echeipesh** [comment]
@pomadchin I'm not sure if I understand this issue. Could you please clarify ?

In my understanding WCS is supposed to return a rasters in format cell values can be used for further processing. Tiff being the most common format. For rendering WMS is the intended protocol, it has support for selecting rendering style and image encoding (PNG, JPG, etc). 

Now given that we're planning on adding [RGB composite MAML operation](https://github.com/geotrellis/maml/issues/114) we may end up in some kind of weird middle ground where one could define a layer to be served by WCS where each pixel is an Int that actually encodes an RGB value. I'm not sure if that's good or bad, just going to happen at this point.

**Comment by pomadchin** [comment]
@echeipesh WCS also supports specification of the output mime type (i.e. image/png instead of a tiff): https://github.com/geotrellis/geotrellis-server/blob/develop/ogc/src/main/scala/geotrellis/server/ogc/wcs/CapabilitiesView.scala#L207

**Comment by echeipesh** [comment]
Ah, so we can add JPG as supported format
