### ISSUE TITLE
Allow serving of MultibandTiles

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-server#2]
Presently, we assume that we are reading `Tile`s.  We should allow `GetCoverage` to produce either `Tile` or `MultibandTile` depending on the layer contents.

**Comment by echeipesh** [comment]
somewhere a long the way of porting logic to use `RasterSource` interface this has been resolved. Said interface always returns `MultibandTile` and we're able to read both `Tile` and `MultibandTile` GeoTrellis layers through it.
