### ISSUE TITLE
GeoTrellisRasterSource temporal build improvements

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-server#219]
At this point [GeoTrellisRasterSource.build function](https://github.com/geotrellis/geotrellis-server/blob/571ea30483b72f643acbbea031e66071cd9680e9/core/src/main/scala/geotrellis/store/GeoTrellisRasterSourceLegacy.scala#L270-L299) creates a set of GeoTrellisRasterSources from a temporal layer, making an assumption that for each time bin there is a single spatial slice. This is not true in the most cases in real world:

1. Instead of an optional temporal resolution we need to pass a list of dates that we know are present in the layer,
2. Have an optional ability to read the list of dates that correspond to each temporal slice from the AttributeStore (this can be done as some custom attribute saved into the AttributeStore).
3. Creation of each new GeoTrellisRasterSource for each date is expensive now, since for each new instance we read all the metadata everytime for each slice, though it is the same across all of them.

**Comment by echeipesh** [comment]
Fresh after reviewing the Query DSL PR these are my notes on what the work probably should be, take it for FWIW:

- We need to apply DSL on something other than `List[RasterSource]` because premature creation of `RasterSource` instances is potentially expensive.
- We can use `List[OgcSourceConf]` since that's what we're reading out anyway.
- `OgcSourceConf` should be extended to provide list of dates for the file.
- For `OgcSourceConf` based on GT RasterSource these should be read from `times` attribute in the AttributeStore for zoom level 0.
- We should expect time in ISO 8601 format

**Comment by CloudNiner** [comment]
I'm releasing my assignment on this as it wasn't strictly necessary in the implementation of #223. Going to move onto other stuff first and pull this again if it becomes a bottleneck.

**Comment by CloudNiner** [comment]
A small SpaceTimeKey layer using landsat 8 data is available at s3://geotrellis-test-non-public/spacetimekey-test, layer name `spacetimekey-test`, zoom `14`. I generated it [with the code here](https://gist.github.com/CloudNiner/adf1c4bd07aa4043b17b5fc9ccf3667e) as part of #157.

**Comment by CloudNiner** [comment]
Copying these "where to start" notes from a conversation with Grisha just now:

1. https://github.com/geotrellis/geotrellis-server/blob/develop/core/src/main/scala/geotrellis/store/GeoTrellisRasterSourceLegacy.scala#L283-L289 temporal resolution is incorrect the fist thing to change is that we need to persist into the attribute store (as a custom field) a list of times that can be selected from the temporal layer // that is acutally what was Eugene talking about 
2. https://github.com/geotrellis/geotrellis-server/blob/develop/core/src/main/scala/geotrellis/store/GeoTrellisRasterSourceLegacy.scala#L294 - it is extremely expensive to create a bucnh of GTRasterSources - we can read all the metadata once and pass it to all rastersource through the constructor (if we can not - fix it so we can ):)
3. it is about List of RasterSources; I don’t know what the return type of a build function should be, but i know that https://github.com/geotrellis/geotrellis-server/blob/fc358bc02c44248d7bc09dee36dc0b558f13b715/ogc-example/src/main/scala/geotrellis/server/ogc/conf/RasterSourceConf.scala#L38-L44 this had to return a single RasterSource (but you’ve merged your commit and thigs have chnaged a bit)

**Comment by echeipesh** [comment]
Just a note, my interpretation is that at the end of this PR its going to be clear how to delete `GeoTrellisRasterSourceLegacy` and use the main-line version of that class. Doing that should be a follow-up issue.
