### ISSUE TITLE
Cleanup GeoTrellis server deps

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-server#228]
We have lots of non used [dependencies](https://github.com/geotrellis/geotrellis-server/blob/4.1.0/project/Dependencies.scala#L56) in this project. Sometimes (i.e. apache commons-io even two times with different names). The task is to remove unused deps and to update them in necessary.

**Comment by jisantuc** [comment]
Do y'all know about

**Comment by pomadchin** [comment]
@jisantuc this task is more trivial tbh; just to remove all unused deps and all duplicate deps from the file. It looks like we were adding it only and never removing unused once. It is also interesting to know that geotrellis-server examples for some reason still depend on Spark :shrug:

**Comment by pomadchin** [comment]
Done here https://github.com/geotrellis/geotrellis-server/pull/334
