### ISSUE TITLE
Create Temporal Test Layer

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-server#247]
We need a temporal test layer. We recently prepared a monthly sentinel mosaic for Baja CA as material for the workshop. This should be ingested into GT temporal layer.

source of cogs: `s3://geotrellis-demo/baja-2018`

target catalog: `s3://geotrellis-demo/catalog/baja-2018`

**Comment by CloudNiner** [comment]
I attempted this once before but the layer sucks. The mosaic generated for the workshop is way better. In any case, here's the code I wrote to generate that, perhaps its useful: https://gist.github.com/CloudNiner/adf1c4bd07aa4043b17b5fc9ccf3667e

The GeoTrellis layer will require that the valid times for the entire layer are available in the AttributeStore in the `times` attribute as a `List[ZonedDateTime]`, which is not covered by the sample code above.

**Comment by CloudNiner** [comment]
🎉
