### ISSUE TITLE
OGC endpoints format parameter and HTTP response mime-type not matching

### ISSUE THREAD

**Issue by micpilon** [geotrellis/geotrellis-server#255]
Geotrellis-Server's HTTP Response Header is always set to respond content in the  `application/octet-stream` format. It would be preferable that the HTTP response mime-type matches the `format` parameter from the GetMap request. 

For instance, .../service=WMS&version=1.3.0&request=GetMap&**format=image/png** ...
would generate a HTTP request with a Response Header set with a `image/png` Content-Type.

**Comment by Marc-AndreDaviault** [comment]
The same thing happens with WCS services

[https://datacube.services.geo.ca/ows/elevation?SERVICE=WCS&VERSION=1.1.1&REQUEST=GetCoverage&FORMAT=image/geotiff&IDENTIFIER=hrdsm&BOUNDINGBOX=-1082312.20988501468673348,1355059.31067213672213256,-53842.37186572709470056,2608174.4939643619582057,urn:ogc:def:crs:EPSG::3979&GRIDBASECRS=urn:ogc:def:crs:EPSG::3979&GRIDCS=urn:ogc:def:cs:OGC:0.0:Grid2dSquareCS&GRIDTYPE=urn:ogc:def:method:WCS:1.1:2dSimpleGrid&GRIDORIGIN=-1082312.20988501468673348,2608174.4939643619582057&GRIDOFFSETS=1528.18698071216590506,-1526.32787246312477691 ](https://datacube.services.geo.ca/ows/elevation?SERVICE=WCS&VERSION=1.1.1&REQUEST=GetCoverage&FORMAT=image/geotiff&IDENTIFIER=hrdsm&BOUNDINGBOX=-1082312.20988501468673348,1355059.31067213672213256,-53842.37186572709470056,2608174.4939643619582057,urn:ogc:def:crs:EPSG::3979&GRIDBASECRS=urn:ogc:def:crs:EPSG::3979&GRIDCS=urn:ogc:def:cs:OGC:0.0:Grid2dSquareCS&GRIDTYPE=urn:ogc:def:method:WCS:1.1:2dSimpleGrid&GRIDORIGIN=-1082312.20988501468673348,2608174.4939643619582057&GRIDOFFSETS=1528.18698071216590506,-1526.32787246312477691 )

FME error: <WCS> Exception detected for the GetCoverage operation, returned Content-Type 'application/octet-stream' is not supported.
