### ISSUE TITLE
Wrong HEIGHT/WIDTH dimensions on GetMap responses for COG layers

### ISSUE THREAD

**Issue by jfbourgon** [geotrellis/geotrellis-server#256]
GetMap responses generated from COG layers sometimes don't have the appropriate HEIGHT/WIDTH dimensions

As example, a request such as the following is producing an output of 256x54 (attached) instead of the expected 256x256.

https://beta.datacube-dev.cgp-pgc.ca/ows/aerial?service=WMS&request=GetMap&layers=salish-1970-1980&styles=&format=image%2Fpng&transparent=false&version=1.3.0&width=256&height=256&crs=EPSG%3A3857&bbox=-13736651.227185596,6339992.874085658,-13697515.468703587,6379128.63256767

![aerial](https://user-images.githubusercontent.com/1030226/80402749-6042a200-888c-11ea-9cfc-af78df74392b.png)

This is producing stretched or misplaced image in web tools such as OpenLayers or Leaflet
![image](https://user-images.githubusercontent.com/1030226/80403124-0ee6e280-888d-11ea-8b26-578dd3b3b1fc.png)

**Comment by jfbourgon** [comment]
Also an example of how the WMS is actually configured
```
salish-1970-1980 = {
        type = "rastersourceconf"
        name = "salish-1970-1980"
        title = "1970-1980 - NAPL photos over Salish area"
        source = "s3://datacube-dev-data/cogs/napl-salish-1970-1980.tif"
        #overview-strategy = "auto-0"
        default-style = "default"
    }
```

**Comment by jfbourgon** [comment]
After further testing, it appears that this issue is present when the GetMap request involves reprojection (e.g. requested CRS is different than the COG reference system) and when the image origin (top-left corner) is outside of the COG coverage.

**Comment by pomadchin** [comment]
It was fixed in terms of https://github.com/locationtech/geotrellis/pull/3252
GeoTiffRasterSource region reproject produced incorrect results.

@jfbourgon could you doublecheck that with the current master the issue is gone? 

The output that I got by using the same parameters that are in the url from the issue description:
```
$ gdalinfo download

Driver: PNG/Portable Network Graphics
Files: download
Size is 256, 256
Coordinate System is `'
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  256.0)
Upper Right (  256.0,    0.0)
Lower Right (  256.0,  256.0)
Center      (  128.0,  128.0)
Band 1 Block=256x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=256x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=256x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=256x1 Type=Byte, ColorInterp=Alpha
```

**Comment by jfbourgon** [comment]
This is also looking good from my end. Attached a screen capture, all tiled WMS images now have the proper dimensions even when a reprojection is involved.
![image](https://user-images.githubusercontent.com/1030226/85041591-2a1cf280-b158-11ea-9d21-b9e74f235e31.png)
