### ISSUE TITLE
Add method to CogUtils

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-server#29]
We have
1. `fetch(uri: String, extent: Extent): IO[Raster[MultibandTile]]`
2. `fetch(uri: String, zoom: Int, x: Int, y: Int): IO[Raster[MultibandTile]]`

It would be nice to add `fetch(uri: String, extent: Extent, cs: CellSize): IO[Raster[MultibandTile]]` so that the nearest overview can be selected and resampled to the provided cellsize's resolution

**Comment by pomadchin** [comment]
We plann to remove this object, RasterSources replace this functionality.
