### ISSUE TITLE
Missing default XML namespace in WMS/WCS responses

### ISSUE THREAD

**Issue by jfbourgon** [geotrellis/geotrellis-server#298]
There is no default XML namespace attribute defined on the root element of WMS/WCS GetCapabilities or other XML responses. The default XML namespace attribute is usually used to inform XML parser about the scope of unprefixed XML element in an XML document.

This may cause XML parser to sometime fail to parse properly XML response. For instance, [owslib ](https://github.com/geopython/OWSLib) library cannot parse WMS/WCS GetCapabilies because of this missing attribute.

The expected behaviour would be to explicitly add the default XML namespace attribute on the root element in WMS/WCS GetCapabilities or other XML responses document as suggested below:

## WMS GetCapabilities
`<WMS_Capabilities xmlns="http://www.opengis.net/wms" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0">`

## WCS GetCapabilities
`<Capabilities xmlns="http://www.opengis.net/wcs/1.1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.1">`

 This was successfully tested using static document derived from actual responses.

**Comment by jisantuc** [comment]
I think that what I've done in #311 should address this, but I'm having a little bit of trouble with testing -- @jfbourgon could you send some OWSLib examples of what was failing?
