### ISSUE TITLE
Hillshade WMS rendering no data and black values discrimination

### ISSUE THREAD

**Issue by micpilon** [geotrellis/geotrellis-server#300]
Hillshade layer rendered with the default built-in style. All cells of value 0 gets rendered as transparent pixel in the resulting png file.
The desired output would be a rendering on which we could preserve black value and still get transparent background where cell value is nodata. 

![image](https://user-images.githubusercontent.com/46534635/87703414-d27aa280-c768-11ea-8d59-75a0b40da971.png)

It seems that this bug is associated with the way renderPng assigns transparency to some bits on the 8-bit value range, including 0 (black).
See: https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/render/PngRenderMethods.scala#L56
https://github.com/geotrellis/geotrellis-server/blob/develop/ogc/src/main/scala/geotrellis/server/ogc/style/ColorRampStyle.scala

**Comment by pomadchin** [comment]
I hope that this PR https://github.com/locationtech/geotrellis/pull/3278 would cover this issue; I'll check it ASAP.

**Comment by pomadchin** [comment]
It looks like it can be a configuration issue with the color ramp application. Try the `clamp-with-color = true` setting in the `layer.styles` definitions!

**Comment by jfbourgon** [comment]
Indeed, it seems it was a configuration issue with the `colorrampconf` style.

Here are conf snippet and related output that confirm this.

### No Clamp 
```
{
                name = "greyscale-noclamp"
                title = "Greyscale Hillshade / Relief ombré en tons de gris (no clamp)"
                type = "colorrampconf"
                colors = ${color-ramps.greyscale}
                stops = 255
                legends = [
                    {
                        format = "image/png"
                        width = 36
                        height = 36
                        online-resource = {
                            type = "simple"
                            href = "https://datacube.services.geo.ca/canada-icon.png"
                        }
                    }
                ]
             }
```

Black values are rendered as transparent pixels and we can see the world imagery underneath.
![image](https://user-images.githubusercontent.com/1030226/90627274-c5c6ef80-e1e9-11ea-908f-aa0d133ee965.png)

### Clamp 
```
{
                name = "greyscale-clamp"
                title = "Greyscale Hillshade / Relief ombré en tons de gris (clamp)"
                type = "colorrampconf"
                colors = ${color-ramps.greyscale}
                stops = 255
                clamp-with-color = true
                legends = [
                    {
                        format = "image/png"
                        width = 36
                        height = 36
                        online-resource = {
                            type = "simple"
                            href = "https://datacube.services.geo.ca/canada-icon.png"
                        }
                    }
                ]
             }
```

Black values are rendered as opaque color as expected.
![image](https://user-images.githubusercontent.com/1030226/90627502-06bf0400-e1ea-11ea-9aba-63c50c264342.png)

Thanks for letting us know about the `clamp-with-color` style property.
