### ISSUE TITLE
Axis Ordering in a wms getmap

### ISSUE THREAD

**Issue by Marc-AndreDaviault** [geotrellis/geotrellis-server#302]
Axis Ordering in a wms getmap 

With geographic coordinate system, the BBOX is always in Lat/Long. It works with EPSG:4326

But we have an error with other projections like 4617 or 4269 and we have to invert the coordinate for long/lat like is it with projected coordinate systems (X,Y) 

this one is working with 4326 (lat/long): 

http://localhost:9000/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=59.99999568489933921,-71.70076515014748963,61.63395983049027649,-69.91442007861941477&CRS=EPSG:4326&WIDTH=973&HEIGHT=890&LAYERS=hrdsm&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

this one make an error with 4269 (lat/long) 

http://localhost:9000/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=58.36603153930821719,-69.91442007861928687,59.99999568489928237,-68.12807500709106989&CRS=EPSG:4269&WIDTH=973&HEIGHT=890&LAYERS=hrdsm&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

but it works if we change to long/lat: 

http://localhost:9000/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-69.91442007861928687,58.36603153930821719,-68.12807500709106989,59.99999568489928237&CRS=EPSG:4269&WIDTH=973&HEIGHT=890&LAYERS=hrdsm&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

4617 and 4269 should be interpreted like geographic coordinate system (lat/long)

**Comment by pomadchin** [comment]
Hi thanks for reporting! Can you point me to the WMS spec? 
And anyway I will look into it a bit later. 

How do yu send queries? Via QGIS?

**Comment by Marc-AndreDaviault** [comment]
> Hi thanks for reporting! Can you point me to the WMS spec?
> And anyway I will look into it a bit later.
> 
> By the way, how do you send queries? Via QGIS?

You can test it with this service : https://datacube.services.geo.ca/ows/elevation?service=wms&request=GetCapabilities 
do you want to see the .conf? 
I use QGIS 
Thanks

**Comment by pomadchin** [comment]
@Marc-AndreDaviault yes, please. If it is possible. I am also wondering, how that got wrong / right? Do you use geotrellis layers? In what projections they are? Ideally I would like to reproduce the behavior.

GT Server doesn't swap query parameters and always uses lat/lon by default for the WMS endpoint (afaik, according to the spec).

**Comment by Marc-AndreDaviault** [comment]
We are using geotrellis layers in 3979. 
here is our .conf (in txt because git doesn't allow to upload .conf) 
[elevation.txt](https://github.com/geotrellis/geotrellis-server/files/5097342/elevation.txt)
