### ISSUE TITLE
Create blessed version of gdal + openjdk image

### ISSUE THREAD

**Issue by jisantuc** [geotrellis/geotrellis-server#60]
The dockerfile here creates a container with gdal compiled with java bindings and other openjdk8 treats: https://github.com/geotrellis/geotrellis-gdal/blob/master/Dockerfile. However, it's a bit ad hoc to depend on in a project setting, so a blessed version in quay or somewhere would be nice to have.

**Comment by jisantuc** [comment]
@geotrellis/operations

**Comment by pomadchin** [comment]
You can republish on quay containers from my repo: 
https://github.com/geotrellis/geotrellis-gdal/pull/22

**Comment by jeancochrane** [comment]
Images are currently available on Quay: https://quay.io/repository/azavea/openjdk-gdal

For future reference, the image definition code lives here: https://github.com/azavea/docker-openjdk-gdal
